from twitter_scraper import get_tweets, Profile  # Twitter scraper
from functools import lru_cache  # Cache feeds
from rfeed import *  # Create RSS feeds
from extensions import * # Insert images into RSS feeds
from flask import make_response  # Tell Flask that it's being sent XML
from banner import get_banner


@lru_cache(maxsize=None)
def twitterToRSS(user):
    items = []  # Create place for items to go.
    profile = Profile(user) # Get profile info for feed.

    for tweet in get_tweets(user, pages=1):
        # Title creation
        if len(tweet['text']) < 50:
            title = tweet['text']
        else:
            title = f"{tweet['text'][:50]}..."
        
        itemExtensions = [] # Create place for extensions to go

        if tweet['entries']['photos']:
            itemExtensions.append(
                MediaItem(
                    tweet['entries']['photos'][0],
                    'image/png',
                    'image',
                    True,
                )
            )
            description = f"<img class='webfeedsFeaturedVisual' src='{tweet['entries']['photos'][0]}'><p>{tweet['text']}</p>"
        else:
            itemExtensions.append(
                MediaItem(
                    profile.profile_photo,
                    'image/png',
                    'image',
                    True,
                )
            )
            description = tweet['text']

        if tweet['isRetweet']:
            author = f"@{tweet['username']}"
            title = f"(Retweet) {title}"
        else:
            author = f'{profile.name} (@{profile.username})'
        # An article for every tweet
        items.append(
            Item(
                title=title,
                link=f"https://twitter.com{tweet['tweetUrl']}",
                description=description,
                author = author,
                guid=Guid(f"https://twitter.com{tweet['tweetUrl']}"),
                pubDate=tweet['time'],
                extensions = itemExtensions
            )
        )

    # Create feed
    feed = Feed(
        title=f"Tweets from {profile.name} (@{profile.username}) - Twitter RSS by Kyle Williams",
        link=f"https://twitter.com/{profile.username}",
        description=
        f"{profile.biography} [Tweets Gathered by Twitter Scraper [twitter-scraper], Feed Generated by rfeed, Hosted By Repl.it]",
        items=items,
        image=Image(
            profile.profile_photo,
            f"Profile picture of {profile.name}",
            f"https://twitter.com/{profile.username}"
        ),
        extensions = [
            MediaContent(),
            Webfeeds(), 
            WebfeedsIcon(profile.profile_photo), 
            WebfeedsCover(get_banner(profile.username))
        ]
    )

    # Tell Flask that it's getting XML
    response = make_response(feed.rss())
    response.headers.set('Content-Type', 'application/rss+xml')

    return response  # Return RSS feed
