from rfeed import * # Create RSS feeds
import GetOldTweets3 as got # Scrape for tweets
from functools import lru_cache # Cache feeds
from flask import make_response # Tell Flask that it's being sent XML

@lru_cache(maxsize=None)
def twitterToRSS(user):
    items = [] # Create place for items to go.

    # Create tweet criteria 
    tweetCriteria = (
        got.manager.TweetCriteria()
        .setUsername(user)
        .setMaxTweets(15)
        .setEmoji("unicode")
    )

    # Gather tweets and make each one a post
    for tweet in got.manager.TweetManager.getTweets(tweetCriteria):
        # Titile creation
        if len(tweet.text) < 50:
            title = (tweet.text)
        else:
            title = (f'{tweet.text[0:50]}...')

        # An article for every tweet
        items.append(
            Item(
                title = title,
                link = tweet.permalink, 
                description = tweet.text,
                author = tweet.username,
                guid = Guid(tweet.permalink),
                pubDate = tweet.date
            )
        )
        
        # Create feed
        feed = Feed(
            title = f'Tweets from {user} - Twitter RSS by Kyle Williams',
            link = f'https://twitter.com/{user}',
            description = 'Tweets Gathered by GetOldTweets3, Feed Generated by rfeed, Hosted By Repl.it',
            items = items
        )

    # Tell Flask that it's getting XML
    response = make_response(feed.rss()) 
    response.headers.set('Content-Type', 'application/rss+xml')

    return response # Return RSS feed

